### ISSUE TITLE
[Question] requireParams in header?

### ISSUE THREAD

**Issue by paambaati** [bryandragon/express-api-helper#3]
Will it be possible to add support for requireParams in the request header too?

**Comment by paambaati** [comment]
AWW YISS! Thanks @bryandragon

**Comment by bryandragon** [comment]
Thanks, @paambaati . I am not able to maintain this project anymore. Would you be interested in adopting it?

**Comment by paambaati** [comment]
@bryandragon That's sad to hear, but yes, I will. Absolutely! How does that work?

**Comment by bryandragon** [comment]
I can transfer the repo to you on GitHub and add you as an owner to the npm package. What is your npm username?

**Comment by paambaati** [comment]
@bryandragon It's gprasannah

**Comment by bryandragon** [comment]
@paambaati All set. Thanks!

**Comment by paambaati** [comment]
@bryandragon Sorry for the late response, but I kinda missed your comment entirely. I've deleted my fork.
